version: '3'
services:
  web:
    build: .
    container_name: flask_train_info_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    command: python app.py
